### ISSUE TITLE
Provide ESM version of rollup plugin

### ISSUE THREAD

**Issue by daron81** [AlexxNB/derver#3]
I have certain workflows with custom rollup plugins, all in ESM format, and do not have rollup transform the configuration file.

In these cases, an ESM version of this server would be very helpful, as it's a very useful tool. Thanks!

**Comment by AlexxNB** [comment]
Hello! Cool that you like Derver. 
I added plugin pacakges for cjs and esm in 0.4.20 - try it out.
```js
import {derver} from 'derver/rollup-plugin'
```

**Comment by offsounder** [comment]
Hmm, this is not working for me. I have a template here I'm trying to use it on: https://github.com/offsounder/stuckup-svelte-template

Since this is a pure ESM project, I used the .mjs rollup config format so that rollup will not transform the config file. I believe the "main" and "module" properties in the package.json only work when transforming. Maybe the "exports" property will work better, but not quite sure.

**Comment by AlexxNB** [comment]
All other plugins you use in your config are CommonJS modules. Derver's plugin also was a CommonJS version. What error message did you get before 0.4.20?

**Comment by offsounder** [comment]
I'm pretty sure all the plugins I'm using have an esm version. The problem is, my project has "type: module" in package.json, so it does not support require calls at all. And my rollup config is not transformed to cjs. I do not remember the exact message.

Feel free to roll back the changes you made, if you wish. I will look into the derver build to see if I can find a solution, and if so, I will submit a PR.

**Comment by AlexxNB** [comment]
It is not about transforming. When you use "type: module" it doesn't mean that Node will import only ESM modules. It only mean that ESM used in your module and when you import CJS(look at rollup-plugin-svelte for example)  module they will work properly. But if you wish to import ESM module, it also must have "module:type" in its package.json.
I'll rollback to cjs only and make named export (I assume that there was a problem with default export).

**Comment by AlexxNB** [comment]
Update on 0.5.1 and use named import 
```js
import {derver} from 'derver/rollup-plugin';
```
It should work with your config.

**Comment by offsounder** [comment]
Perfect, that worked. Thanks!

I did not know the details of importing CJS from pure ESM node projects. I'm curious, was it working without the "exports" property in your package.json? Correct me if I'm wrong, but node ignores the distinction btw "main" and "module" properties.

**Comment by AlexxNB** [comment]
An "exports" field doesn't matter here. I just added this to move plugin in dist folder and have shorten import path.
It is not clear when you use ESM modules in node even at present time. If you have a project where you writed `type:module` in your  `package.json` Node will import files from `module` or `exports.import` fields, BUT this modules MUST have `type:module` in their `packaje.json`s` also. But you still can `import` any CommonJS module without any preparations.
